# Generated by Django 3.1.7 on 2021-03-19 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astronauts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='astronaut',
            name='time_in_space',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
