# Generated by Django 3.1.7 on 2021-03-31 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='text',
            field=models.TextField(default='', max_length=30000),
            preserve_default=False,
        ),
    ]
