# Generated by Django 3.2.3 on 2021-08-04 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'Аккаунт', 'verbose_name_plural': 'Аккаунты'},
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=32, verbose_name='Имя'),
        ),
    ]
