# Generated by Django 3.2.3 on 2021-07-10 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20210709_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='avg_rating_previous',
            field=models.FloatField(default=0),
        ),
    ]
