# Generated by Django 3.2.3 on 2021-06-26 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='film_name',
            field=models.TextField(choices=[('US', 'United States'), ('FR', 'France'), ('CN', 'China'), ('RU', 'Russia'), ('IT', 'Italy')], null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='score',
            field=models.TextField(),
        ),
    ]
