# Generated by Django 3.2.3 on 2021-06-26 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_reviews', '0003_auto_20210626_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviename',
            name='film_name',
            field=models.TextField(),
        ),
    ]
