# Generated by Django 3.2.3 on 2021-06-26 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_reviews', '0005_alter_movie_film_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='film_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movie_reviews.moviename'),
        ),
    ]
