# Generated by Django 3.2.3 on 2021-06-27 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_reviews', '0006_alter_movie_film_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviename',
            name='film_description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
