# Generated by Django 3.2.3 on 2021-06-28 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_reviews', '0007_moviename_film_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['name'], 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterModelOptions(
            name='moviename',
            options={'verbose_name': 'Фильм', 'verbose_name_plural': 'Фильмы'},
        ),
        migrations.AddField(
            model_name='moviename',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.TextField(verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='score',
            field=models.TextField(verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='moviename',
            name='film_description',
            field=models.TextField(verbose_name='Описание фильма'),
        ),
        migrations.AlterField(
            model_name='moviename',
            name='film_name',
            field=models.TextField(verbose_name='Название фильма'),
        ),
    ]
