# Generated by Django 3.2.3 on 2021-06-28 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_reviews', '0008_auto_20210628_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviename',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='URL'),
        ),
    ]
