# Generated by Django 3.2.3 on 2021-06-28 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_reviews', '0010_movie_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviename',
            name='slug',
        ),
    ]
