# Generated by Django 3.2.3 on 2021-07-01 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_reviews', '0014_remove_movie_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviename',
            name='photo',
            field=models.ImageField(default=None, upload_to='photos/%Y/%m/%d'),
        ),
    ]
