# Generated by Django 3.2.3 on 2021-07-01 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_reviews', '0015_moviename_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviename',
            name='photo',
            field=models.ImageField(upload_to='photos/%Y/%m/%d'),
        ),
    ]
