# Generated by Django 3.2.3 on 2021-07-01 18:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movie_reviews', '0016_alter_moviename_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='time_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
